title: Web Developer
name: Jordan Carney
email: jordan@jordancarney.com
description: >- # this means to ignore newlines until "baseurl:"
  JavaScript developer currently focused on React, Redux, and Node. Lets chat!
baseurl: "" 
url: "https://jordancarney.com"
freecodecame_username: jordancarney1
twitter_username: jordancarney1
github_username:  jordancarney1
linkedin_username: jordancarney

collections:
  - projects

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass